# Generated by Django 2.2.28 on 2022-10-22 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats_Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField(blank=True, null=True)),
                ('transaction_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.IntegerField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('forget_passtoken', models.CharField(default=False, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('verify', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chats_Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('other_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='EsayPayApp.Other_User')),
                ('self_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EsayPayApp.Chats_Transactions')),
            ],
        ),
        migrations.CreateModel(
            name='BANK',
            fields=[
                ('b_key', models.AutoField(primary_key=True, serialize=False)),
                ('b_name', models.CharField(max_length=100)),
                ('b_user_name', models.CharField(max_length=100)),
                ('b_user_email', models.EmailField(max_length=100)),
                ('b_account', models.IntegerField()),
                ('b_ifsc', models.IntegerField()),
                ('b_img', models.CharField(default=False, max_length=500)),
                ('b_type', models.CharField(default=False, max_length=100)),
                ('b_phone', models.CharField(max_length=11)),
                ('b_balance', models.IntegerField(blank=True)),
                ('b_user_id', models.IntegerField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
