# Generated by Django 2.2.28 on 2022-10-24 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EsayPayApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_first', to=settings.AUTH_USER_MODEL)),
                ('user_second', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='chats_chat',
            name='other_user',
        ),
        migrations.RemoveField(
            model_name='chats_chat',
            name='self_user',
        ),
        migrations.DeleteModel(
            name='Other_User',
        ),
        migrations.AddField(
            model_name='chats_chat',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='EsayPayApp.Conversation'),
            preserve_default=False,
        ),
    ]
