# Generated by Django 2.2.28 on 2022-10-24 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EsayPayApp', '0002_auto_20221024_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chats_chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EsayPayApp.Conversation'),
        ),
    ]
